name: Matrix Test
on:
  push:
jobs:
  build-matrix:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Matrix
        id: create-matrix
        run: |
          $params = Get-Content -Path ./params.txt
          $aliases = "["
          $persons = $params.split("|")
          foreach ($person in $persons)
          {
            $attributes = $person.split(",")
            foreach ($attribute in $attributes)
            {
              # Split the key from the value
              $keyAndValue = $attribute.split("=")
              $key = $keyAndValue[0]
              $value = $keyAndValue[1]
              if($key.ToLower() -eq "alias")
              {
                echo "Testing the following person: $value"
                $aliases += '"'
                $aliases += $value.Trim()
                $aliases += '",'
              }
            }
          }
          $aliases = $aliases.Substring(0, $aliases.Length-1)
          $aliases += "]"
          echo $aliases
          echo aliases=$aliases >> $env:GITHUB_OUTPUT
    outputs:
      aliases: ${{ steps.create-matrix.outputs.aliases }}          
  build-matrix-matrix:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    needs:
      - build-matrix
    strategy:
      fail-fast: false
      matrix:
        product: ${{ fromJson(needs.build-matrix.outputs.aliases) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Matrix
        id: create-matrix-matrix
        run: |
          $params = Get-Content -Path ./params.txt
          $aliases = "["
          $persons = $params.split("|")
          foreach ($person in $persons)
          
